### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by YuhangZh** [meiqihu/BCG-Net#1]
Hello, I would like to ask a question about what data is stored in the mat dataset endmember. How should I get this data if I use other dataset. Is it convenient to provide the code to generate this data?

**Comment by meiqihu** [comment]
Actually, the endmember is extracted by VCA method. Any publich VCA code can be found in public resource. And i can send the VCA code to you if you need it.

2023-07-07 17:28:40YuhangZh ***@***.***>写道：

Hello, I would like to ask a question about what data is stored in the mat dataset endmember. How should I get this data if I use other dataset. Is it convenient to provide the code to generate this data?

**Comment by YuhangZh** [comment]
I need VCA related code, please also send it to my email. Your code is a great help to my work, thank you very much.

**Comment by YuhangZh** [comment]
I need VCA related code, please also send it to my email. Your code is a great help to my work, thank you very much.

**Comment by meiqihu** [comment]
The Hysime, VCA, and FCLS have been uploaded.😀

**Comment by meiqihu** [comment]
The VCA code has been uploaded. 

***@***.***

2023-07-08 21:31:17YuhangZh ***@***.***>写道：

I need VCA related code, please also send it to my email. Your code is a great help to my work, thank you very much.
